version: '3.8'

services:
  server:
    build: 
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    volumes:
      - ./server:/app
      - /app/node_modules
    networks:
      - sudoku-network

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_SERVER_URL=http://server:3001
    volumes:
      - ./client:/app
      - /app/node_modules
    depends_on:
      - server
    networks:
      - sudoku-network

networks:
  sudoku-network:
    driver: bridge 